### ISSUE TITLE
dry-auto_inject needs new docs

### ISSUE THREAD

**Issue by solnic** [dry-rb/dry-auto_inject#66]
We have a bunch of nice features that are completely undocumented :(
### TODO
- [x] ~~document how to create a custom injector with options~~ no need for this for now (after all)
- [x] document `kwargs` strategy
- [x] document `*args` strategy
- [ ] point to dry-system
